name: Docker build

on:
  push:
    branches:
      - main
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Load environment variables
        uses: k15g/action-load-env@edge

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build
        run: make build

      - name: Push egde images
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: make push-edge

      - name: Push images
        if: "startsWith(github.ref, 'refs/tags/')"
        run: make push-release