name: Docker build

on:
  push:
    branches:
      - main
    paths:
      - .env/HTMLPROOFER_VERSION
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Load environment variables
        uses: k15g/action-load-env@edge

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build
        run: make build

      - name: Push egde images
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: make push-edge

      - name: Push images
        if: "startsWith(github.ref, 'refs/tags/')"
        run: make push-release

      - name: Update README
        if: "startsWith(github.ref, 'refs/tags/')"
        run: cat template/README.md | envsubst > README.md

      - name: Commit and push potential changes
        uses: actions-js/push@master
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          message: HTMLProofer version ${{ steps.source.outputs.version }}
          github_token: ${{ secrets.BOT_TOKEN }}
          branch: main
          author_name: ${{ secrets.BOT_USERNAME }}
          author_email: ${{ secrets.BOT_EMAIL }}