name: Updater

on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Update
      run: sh hooks/updater
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
